# Generated by Django 4.1.2 on 2022-10-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status_ok', models.BooleanField()),
                ('start_time', models.DateTimeField(null=True)),
                ('execution_time', models.IntegerField(null=True)),
            ],
        ),
    ]
