# Generated by Django 4.1 on 2022-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePlayerStatsFBREF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_birth', models.DateField()),
                ('team_name', models.CharField(max_length=30)),
                ('original_position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CMD', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('FW', 'Forward'), ('UKW', 'Unknown')], default='UKW', max_length=3)),
                ('matches_played', models.IntegerField()),
                ('as_starter', models.IntegerField()),
                ('minutes_played', models.IntegerField()),
            ],
        ),
    ]
