# Generated by Django 4.1 on 2023-02-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseteam',
            name='date_birth',
        ),
    ]
