# Generated by Django 4.1.2 on 2022-10-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=5)),
                ('date_birth', models.DateField()),
                ('team_name', models.CharField(max_length=30)),
                ('original_position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CMD', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('FW', 'Forward'), ('UKW', 'Unknown')], default='UKW', max_length=3)),
            ],
        ),
    ]
