# Generated by Django 4.1 on 2022-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_baseplayerstatsfbref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseplayerstatsfbref',
            name='original_position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Center Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('DF,MF', 'Defensive Midfielder'), ('MF', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('FW', 'Forward'), ('UKW', 'Unknown')], default='UKW', max_length=10),
        ),
    ]
