# Generated by Django 4.1 on 2022-12-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_baseplayerstatsfbref_original_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseplayerstatsfbref',
            name='as_starter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseplayerstatsfbref',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='baseplayerstatsfbref',
            name='matches_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseplayerstatsfbref',
            name='minutes_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseplayerstatsfbref',
            name='original_position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Center Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('DF,MF', 'Defensive Midfielder'), ('MF', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('FW', 'Forward'), ('UKW', 'Unknown')], default='UKW', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='baseplayerstatsfbref',
            name='team_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
