# Generated by Django 4.1 on 2022-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_baseplayerstatsfbref_as_starter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='exp_goals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='exp_goals_assists',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='exp_non_pen_goals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='expected_non_pen_goals_assists',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='non_pen_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='penalty_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='penalty_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='red_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='yellow_cards',
            field=models.IntegerField(null=True),
        ),
    ]
