# Generated by Django 4.1 on 2023-02-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_baseplayerstatsfbref_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='progressive_carries',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='progressive_passes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseplayerstatsfbref',
            name='progressive_passes_received',
            field=models.FloatField(null=True),
        ),
    ]
